In [1]:
!pip list

Package                 Version
----------------------- ---------
absl-py                 0.13.0
anyio                   3.3.0
argon2-cffi             20.1.0
astunparse              1.6.3
async-generator         1.10
attrs                   21.2.0
Babel                   2.9.1
backcall                0.2.0
bleach                  4.1.0
cached-property         1.5.2
cachetools              4.2.2
certifi                 2021.5.30
cffi                    1.14.6
charset-normalizer      2.0.4
clang                   5.0
colorama                0.4.4
contextvars             2.4
dataclasses             0.8
decorator               5.0.9
defusedxml              0.7.1
entrypoints             0.3
flatbuffers             1.12
gast                    0.4.0
google-auth             1.35.0
google-auth-oauthlib    0.4.5
google-pasta            0.2.0
grpcio                  1.39.0
h5py                    3.1.0
idna                    3.2
immutables              0.16
importlib-metadata      4.7.1
ipykern

In [2]:
import sys
sys.executable

'c:\\users\\ysilhouette\\documents\\pyenv\\py_365_tf_2\\scripts\\python.exe'

In [3]:
import tensorflow as tf 

In [4]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


True

In [5]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [10]:
tf.__version__

'2.6.0'

In [11]:
x = [[1.]]
m = tf.matmul(x,x)
print(m)

tf.Tensor([[1.]], shape=(1, 1), dtype=float32)


In [12]:
x = tf.constant([[1,9],[3,6]])
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 9],
       [3, 6]])>

In [14]:
x = tf.add(x,1)

In [15]:
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2, 10],
       [ 4,  7]])>

In [16]:
x.numpy()

array([[ 2, 10],
       [ 4,  7]])

In [17]:
tf.cast(x, tf.float32)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 2., 10.],
       [ 4.,  7.]], dtype=float32)>

In [18]:
import numpy as np

In [20]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [21]:
np.zeros(2)

array([0., 0.])

In [22]:
np.ones(2)

array([1., 1.])

In [23]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [24]:
x1 = np.ones([2,2])

In [25]:
x1

array([[1., 1.],
       [1., 1.]])

In [26]:
tf.multiply(x1,2)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2., 2.],
       [2., 2.]])>