In [1]:
import tensorflow as tf

In [2]:
from tensorflow import keras

In [3]:
import numpy as np

### Embedding

```
tf.keras.layers.Embedding(
    input_dim, output_dim, embeddings_initializer='uniform',
    embeddings_regularizer=None, activity_regularizer=None,
    embeddings_constraint=None, mask_zero=False, input_length=None, **kwargs
)
```

In [4]:
vocab_size=10
out_dim=10
batch_size =32
units = 32

In [5]:

# 其中1000表示input_dimension,也就是词汇表的大小，size of vocabulary
embed = keras.layers.Embedding(input_dim=vocab_size,output_dim=out_dim)
embed

In [16]:
test_x=np.random.randint(10,size=(batch_size,2))
test_x

array([[2, 4],
       [6, 4],
       [7, 8],
       [5, 3],
       [5, 1],
       [7, 0],
       [7, 9],
       [4, 1],
       [3, 6],
       [9, 1],
       [9, 4],
       [1, 7],
       [3, 2],
       [3, 3],
       [3, 3],
       [0, 6],
       [7, 7],
       [4, 1],
       [9, 3],
       [7, 6],
       [8, 0],
       [7, 8],
       [3, 3],
       [7, 5],
       [3, 1],
       [8, 3],
       [7, 8],
       [3, 2],
       [2, 3],
       [1, 1],
       [5, 6],
       [3, 0]])

In [17]:
test_x.shape

(32, 2)

In [18]:
embed(test_x)

<tf.Tensor: shape=(32, 2, 10), dtype=float32, numpy=
array([[[-0.01372281, -0.02558281,  0.03040667,  0.01933027,
          0.00082835, -0.03225042,  0.02454338, -0.01896745,
          0.01792786,  0.01688181],
        [ 0.0167869 , -0.0241568 , -0.01391283, -0.03121316,
          0.02011046,  0.00024397, -0.02705981, -0.02816738,
          0.02115688, -0.03088739]],

       [[ 0.04986143, -0.04900012, -0.01908988,  0.02565249,
          0.02327783, -0.02456356, -0.02516657,  0.04759378,
          0.04027304, -0.0461815 ],
        [ 0.0167869 , -0.0241568 , -0.01391283, -0.03121316,
          0.02011046,  0.00024397, -0.02705981, -0.02816738,
          0.02115688, -0.03088739]],

       [[ 0.01573142, -0.02681882, -0.02125452, -0.01403191,
          0.03197802,  0.02645608, -0.04975129, -0.03916116,
         -0.02402239, -0.03080901],
        [ 0.017586  ,  0.03954829, -0.0106926 , -0.04188658,
          0.04094392, -0.03261347, -0.01800026,  0.02243816,
         -0.0490546 ,  0.021027

In [19]:
np.array([[0,1],[1,2]])

array([[0, 1],
       [1, 2]])

In [20]:
embed(np.array([[0,1],[1,2]]))

<tf.Tensor: shape=(2, 2, 10), dtype=float32, numpy=
array([[[ 0.04232648,  0.01709416, -0.00094085, -0.01240324,
          0.00967775,  0.00040231,  0.0060554 ,  0.02592048,
          0.00393624, -0.02889873],
        [ 0.0430559 , -0.0014899 , -0.04370895,  0.03357038,
          0.01690192, -0.02604136, -0.04773562,  0.00408036,
          0.01696665,  0.03484503]],

       [[ 0.0430559 , -0.0014899 , -0.04370895,  0.03357038,
          0.01690192, -0.02604136, -0.04773562,  0.00408036,
          0.01696665,  0.03484503],
        [-0.01372281, -0.02558281,  0.03040667,  0.01933027,
          0.00082835, -0.03225042,  0.02454338, -0.01896745,
          0.01792786,  0.01688181]]], dtype=float32)>

### GRU

```
tf.keras.layers.GRU(
    units, activation='tanh', recurrent_activation='sigmoid',
    use_bias=True, kernel_initializer='glorot_uniform',
    recurrent_initializer='orthogonal',
    bias_initializer='zeros', kernel_regularizer=None,
    recurrent_regularizer=None, bias_regularizer=None, activity_regularizer=None,
    kernel_constraint=None, recurrent_constraint=None, bias_constraint=None,
    dropout=0.0, recurrent_dropout=0.0, return_sequences=False, return_state=False,
    go_backwards=False, stateful=False, unroll=False, time_major=False,
    reset_after=True, **kwargs
)
```

- 参数

```
units 正整数，输出空间的维度。
activation 要使用的激活函数。默认值：双曲正切(tanh)。如果您通过 None ，则不会应用激活(即 "linear" 激活：a(x) = x )。
recurrent_activation 用于循环步骤的激活函数。默认值：sigmoid (sigmoid)。如果您通过 None ，则不会应用激活(即 "linear" 激活：a(x) = x )。
use_bias 布尔值，(默认 True )，图层是否使用偏置向量。
kernel_initializer kernel 权重矩阵的初始化器，用于输入的线性变换。默认值：glorot_uniform。
recurrent_initializer recurrent_kernel 权重矩阵的初始化器，用于循环状态的线性变换。默认值：orthogonal。
bias_initializer 偏置向量的初始化器。默认值：zeros。
kernel_regularizer 应用于kernel 权重矩阵的正则化函数。默认值：None。
recurrent_regularizer 应用于recurrent_kernel 权重矩阵的正则化函数。默认值：None。
bias_regularizer 应用于偏置向量的正则化函数。默认值：None。
activity_regularizer 应用于层输出的正则化函数("activation")。默认值：None。
kernel_constraint 应用于kernel 权重矩阵的约束函数。默认值：None。
recurrent_constraint 应用于recurrent_kernel 权重矩阵的约束函数。默认值：None。
bias_constraint 应用于偏置向量的约束函数。默认值：None。
dropout 在 0 和 1 之间浮点数。为输入的线性变换而下降的单位分数。默认值：0。
recurrent_dropout 在 0 和 1 之间浮点数。用于循环状态的线性变换的单位的分数。默认值：0。
return_sequences 布尔值。是返回输出序列中的最后一个输出，还是返回完整序列。默认值：False。
return_state 布尔值。是否返回除了输出之外的最后一个状态。默认值：False。
go_backwards 布尔值(默认 False )。如果为 True，则反向处理输入序列并返回反向序列。
stateful 布尔值(默认为 False)。如果为 True，则批次中索引 i 处每个样本的最后状态将用作下一批中索引 i 的样本的初始状态。
unroll 布尔值(默认为 False)。如果为 True，则网络将展开，否则将使用符号循环。展开可以speed-up一个RNN，虽然它往往更多memory-intensive。展开仅适用于短序列。
time_major inputs 和 outputs 张量的形状格式。如果为 True，输入和输出的形状将是 [timesteps, batch, feature] ，而在 False 情况下，它将是 [batch, timesteps, feature] 。使用time_major = True 效率更高一些，因为它避免了 RNN 计算开始和结束时的转置。但是，大多数 TensorFlow 数据是 batch-major，因此默认情况下，此函数接受输入并以 batch-major 形式发出输出。
reset_after GRU 约定(是否在矩阵乘法之后或之前应用重置门)。 False = "before"，True = "after"(默认和 cuDNN 兼容)。
```

- 属性

```
activation
bias_constraint
bias_initializer
bias_regularizer
dropout
implementation
kernel_constraint
kernel_initializer
kernel_regularizer
recurrent_activation
recurrent_constraint
recurrent_dropout
recurrent_initializer
recurrent_regularizer
reset_after
states
units
use_bias
```

有关 RNN API 使用的详细信息，请参阅 Keras RNN API 指南。

根据可用的运行时硬件和约束，该层将选择不同的实现(基于 cuDNN 或 pure-TensorFlow)以最大化性能。如果 GPU 可用并且该层的所有参数都满足 cuDNN 内核的要求(详见下文)，则该层将使用快速 cuDNN 实现。

使用 cuDNN 实现的要求是：
```
activation == tanh
recurrent_activation == sigmoid
recurrent_dropout == 0
unroll 是 False
use_bias 是 True
reset_after 是 True
```
输入，如果使用掩码，严格来说是right-padded。
在最外层的上下文中启用了即刻执行。
GRU 实现有两种变体。默认的基于 v3，并在矩阵乘法之前将重置门应用于隐藏状态。另一种是根据原件，顺序颠倒。

第二个变体与 CuDNNGRU (GPU-only) 兼容，并允许在 CPU 上进行推理。因此，它对 kernel 和 recurrent_kernel 有不同的偏见。要使用此变体，请设置 reset_after=True 和 recurrent_activation='sigmoid' 。

例如：
```
inputs = tf.random.normal([32, 10, 8])
gru = tf.keras.layers.GRU(4)
output = gru(inputs)
print(output.shape)
(32, 4)
gru = tf.keras.layers.GRU(4, return_sequences=True, return_state=True)
whole_sequence_output, final_state = gru(inputs)
print(whole_sequence_output.shape)
(32, 10, 4)
print(final_state.shape)
(32, 4)
```

调用参数：
inputs:一个 3D 张量，有形状[batch, timesteps, feature].
mask: 形状的二进制张量[samples, timesteps]指示是否应屏蔽给定时间步(可选，默认为None)。个人True条目指示应使用相应的时间步长，而Falseentry 表示应该忽略相应的时间步长。
training:Python 布尔值，指示层应该在训练模式还是推理模式下运行。此参数在调用时传递给单元格。这仅在以下情况下才相关dropout或者recurrent_dropout使用(可选，默认为None)。
initial_state：要传递给单元格第一次调用的初始状态张量列表(可选，默认为None这会导致创建zero-filled 初始状态张量)。

In [21]:
gru = keras.layers.GRU(units, return_sequences=True, return_state=True,
                                       recurrent_initializer="glorot_uniform")

In [22]:
help(gru)

Help on GRU in module keras.layers.recurrent_v2 object:

class GRU(keras.layers.recurrent.DropoutRNNCellMixin, keras.layers.recurrent.GRU)
 |  Gated Recurrent Unit - Cho et al. 2014.
 |  
 |  See [the Keras RNN API guide](https://www.tensorflow.org/guide/keras/rnn)
 |  for details about the usage of RNN API.
 |  
 |  Based on available runtime hardware and constraints, this layer
 |  will choose different implementations (cuDNN-based or pure-TensorFlow)
 |  to maximize the performance. If a GPU is available and all
 |  the arguments to the layer meet the requirement of the CuDNN kernel
 |  (see below for details), the layer will use a fast cuDNN implementation.
 |  
 |  The requirements to use the cuDNN implementation are:
 |  
 |  1. `activation` == `tanh`
 |  2. `recurrent_activation` == `sigmoid`
 |  3. `recurrent_dropout` == 0
 |  4. `unroll` is `False`
 |  5. `use_bias` is `True`
 |  6. `reset_after` is `True`
 |  7. Inputs, if use masking, are strictly right-padded.
 |  8. Eager 

In [23]:
embed_x =embed(test_x)
embed_x

<tf.Tensor: shape=(32, 2, 10), dtype=float32, numpy=
array([[[-0.01372281, -0.02558281,  0.03040667,  0.01933027,
          0.00082835, -0.03225042,  0.02454338, -0.01896745,
          0.01792786,  0.01688181],
        [ 0.0167869 , -0.0241568 , -0.01391283, -0.03121316,
          0.02011046,  0.00024397, -0.02705981, -0.02816738,
          0.02115688, -0.03088739]],

       [[ 0.04986143, -0.04900012, -0.01908988,  0.02565249,
          0.02327783, -0.02456356, -0.02516657,  0.04759378,
          0.04027304, -0.0461815 ],
        [ 0.0167869 , -0.0241568 , -0.01391283, -0.03121316,
          0.02011046,  0.00024397, -0.02705981, -0.02816738,
          0.02115688, -0.03088739]],

       [[ 0.01573142, -0.02681882, -0.02125452, -0.01403191,
          0.03197802,  0.02645608, -0.04975129, -0.03916116,
         -0.02402239, -0.03080901],
        [ 0.017586  ,  0.03954829, -0.0106926 , -0.04188658,
          0.04094392, -0.03261347, -0.01800026,  0.02243816,
         -0.0490546 ,  0.021027

In [24]:
init_hidden = tf.zeros((batch_size, units))
init_hidden

<tf.Tensor: shape=(32, 32), dtype=float32, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>

In [26]:
 output_x, state_x=gru(embed_x,init_hidden)

In [27]:
output_x

<tf.Tensor: shape=(32, 2, 32), dtype=float32, numpy=
array([[[-4.85169748e-03, -2.57038767e-03, -8.96145124e-03, ...,
         -1.83440570e-03, -2.90107727e-03, -6.40665705e-04],
        [-1.96462311e-03,  2.77515827e-03, -9.67804808e-03, ...,
         -1.22395717e-03,  7.60538969e-05,  1.93269085e-03]],

       [[-5.28128818e-03, -2.38672365e-04, -8.03723745e-03, ...,
          4.58990689e-03,  6.36845455e-03, -1.08799394e-02],
        [-3.79649969e-03,  4.64652292e-03, -1.02896094e-02, ...,
          3.69140739e-03,  3.50512727e-03, -2.44601769e-03]],

       [[ 2.80382577e-04, -2.53000576e-03, -1.89401791e-03, ...,
          9.92462505e-04,  9.77116055e-04,  1.20198831e-03],
        [-2.03997735e-03, -3.74573423e-03,  1.02432910e-02, ...,
          2.79853889e-03, -1.49048585e-02,  7.12145120e-04]],

       ...,

       [[-5.52272191e-03,  3.88177927e-03,  3.29490402e-03, ...,
          1.22958859e-02, -1.11580586e-04, -5.73109370e-03],
        [-1.01384930e-02,  6.25167461e-03,  5.

In [28]:
state_x

<tf.Tensor: shape=(32, 32), dtype=float32, numpy=
array([[-1.9646231e-03,  2.7751583e-03, -9.6780481e-03, ...,
        -1.2239572e-03,  7.6053897e-05,  1.9326909e-03],
       [-3.7964997e-03,  4.6465229e-03, -1.0289609e-02, ...,
         3.6914074e-03,  3.5051273e-03, -2.4460177e-03],
       [-2.0399773e-03, -3.7457342e-03,  1.0243291e-02, ...,
         2.7985389e-03, -1.4904859e-02,  7.1214512e-04],
       ...,
       [-1.0138493e-02,  6.2516746e-03,  5.4155439e-03, ...,
         1.8269716e-02,  7.0067000e-04, -7.3074512e-03],
       [-5.7472293e-03,  2.6640152e-03, -1.1608106e-02, ...,
         5.7030311e-03,  6.4014150e-03, -6.7572892e-03],
       [-9.2545402e-04,  1.3008846e-03,  5.4753167e-03, ...,
         4.8077025e-04, -5.5369325e-03, -5.2091442e-03]], dtype=float32)>

### tf.expand_dims()函数用于给函数增加维度。

```
tf.expand_dims()函数用于给函数增加维度。
tf.expand_dims(
    input,
    axis=None,
    name=None,
    dim=None
)
```
参数：
```
input是输入张量。
axis是指定扩大输入张量形状的维度索引值。
dim等同于轴，一般不推荐使用。
```
函数的功能是在给定一个input时，在axis轴处给input增加一个维度。

- axis：

给定张量输入input，此操作为选择维度索引值，在输入形状的维度索引值的轴处插入1的维度。 维度索引值的轴从零开始; 如果您指定轴是负数，则从最后向后进行计数，也就是倒数。