In [1]:
import tensorflow as tf

In [2]:
from tensorflow import keras

In [3]:
import numpy as np

### Embedding

```
tf.keras.layers.Embedding(
    input_dim, output_dim, embeddings_initializer='uniform',
    embeddings_regularizer=None, activity_regularizer=None,
    embeddings_constraint=None, mask_zero=False, input_length=None, **kwargs
)
```

In [4]:
vocab_size=10
out_dim=10
batch_size =32
units = 32

In [5]:

# 其中1000表示input_dimension,也就是词汇表的大小，size of vocabulary
embed = keras.layers.Embedding(input_dim=vocab_size,output_dim=out_dim)
embed

In [6]:
test_x=np.random.randint(10,size=(batch_size,2))
test_x

array([[7, 8],
       [7, 1],
       [0, 0],
       [8, 8],
       [9, 9],
       [6, 4],
       [8, 1],
       [9, 7],
       [8, 5],
       [8, 9],
       [7, 5],
       [2, 2],
       [4, 9],
       [9, 8],
       [3, 2],
       [2, 4],
       [3, 6],
       [0, 1],
       [8, 2],
       [2, 9],
       [4, 0],
       [3, 9],
       [5, 1],
       [0, 5],
       [9, 9],
       [4, 2],
       [9, 8],
       [4, 9],
       [3, 9],
       [7, 9],
       [4, 3],
       [6, 4]])

In [7]:
test_x.shape

(32, 2)

In [8]:
embed(test_x)

<tf.Tensor: shape=(32, 2, 10), dtype=float32, numpy=
array([[[-0.04455454,  0.04463908,  0.04506776,  0.02344776,
         -0.04919156, -0.04341774, -0.0441567 ,  0.01678076,
         -0.01249163,  0.0438653 ],
        [-0.0176981 , -0.02319922,  0.01458457, -0.02064159,
          0.01132836,  0.00938264, -0.04608802, -0.01562606,
          0.04889529, -0.02774007]],

       [[-0.04455454,  0.04463908,  0.04506776,  0.02344776,
         -0.04919156, -0.04341774, -0.0441567 ,  0.01678076,
         -0.01249163,  0.0438653 ],
        [ 0.01003499,  0.0396397 , -0.02368988, -0.0179203 ,
         -0.02464662,  0.04157648,  0.00130557,  0.04739784,
         -0.01525488, -0.04575637]],

       [[-0.02027046,  0.04145514,  0.00930665,  0.03462258,
          0.03842961,  0.00826417, -0.04229715, -0.02322576,
          0.01806841,  0.03489599],
        [-0.02027046,  0.04145514,  0.00930665,  0.03462258,
          0.03842961,  0.00826417, -0.04229715, -0.02322576,
          0.01806841,  0.034895

In [9]:
np.array([[0,1],[1,2]])

array([[0, 1],
       [1, 2]])

In [10]:
embed(np.array([[0,1],[1,2]]))

<tf.Tensor: shape=(2, 2, 10), dtype=float32, numpy=
array([[[-0.02027046,  0.04145514,  0.00930665,  0.03462258,
          0.03842961,  0.00826417, -0.04229715, -0.02322576,
          0.01806841,  0.03489599],
        [ 0.01003499,  0.0396397 , -0.02368988, -0.0179203 ,
         -0.02464662,  0.04157648,  0.00130557,  0.04739784,
         -0.01525488, -0.04575637]],

       [[ 0.01003499,  0.0396397 , -0.02368988, -0.0179203 ,
         -0.02464662,  0.04157648,  0.00130557,  0.04739784,
         -0.01525488, -0.04575637],
        [-0.00401158,  0.02691047, -0.04453013, -0.03804395,
         -0.04162438, -0.01433868, -0.04531867,  0.02753348,
          0.01271724, -0.02674476]]], dtype=float32)>

### GRU

```
tf.keras.layers.GRU(
    units, activation='tanh', recurrent_activation='sigmoid',
    use_bias=True, kernel_initializer='glorot_uniform',
    recurrent_initializer='orthogonal',
    bias_initializer='zeros', kernel_regularizer=None,
    recurrent_regularizer=None, bias_regularizer=None, activity_regularizer=None,
    kernel_constraint=None, recurrent_constraint=None, bias_constraint=None,
    dropout=0.0, recurrent_dropout=0.0, return_sequences=False, return_state=False,
    go_backwards=False, stateful=False, unroll=False, time_major=False,
    reset_after=True, **kwargs
)
```

- 参数

```
units 正整数，输出空间的维度。
activation 要使用的激活函数。默认值：双曲正切(tanh)。如果您通过 None ，则不会应用激活(即 "linear" 激活：a(x) = x )。
recurrent_activation 用于循环步骤的激活函数。默认值：sigmoid (sigmoid)。如果您通过 None ，则不会应用激活(即 "linear" 激活：a(x) = x )。
use_bias 布尔值，(默认 True )，图层是否使用偏置向量。
kernel_initializer kernel 权重矩阵的初始化器，用于输入的线性变换。默认值：glorot_uniform。
recurrent_initializer recurrent_kernel 权重矩阵的初始化器，用于循环状态的线性变换。默认值：orthogonal。
bias_initializer 偏置向量的初始化器。默认值：zeros。
kernel_regularizer 应用于kernel 权重矩阵的正则化函数。默认值：None。
recurrent_regularizer 应用于recurrent_kernel 权重矩阵的正则化函数。默认值：None。
bias_regularizer 应用于偏置向量的正则化函数。默认值：None。
activity_regularizer 应用于层输出的正则化函数("activation")。默认值：None。
kernel_constraint 应用于kernel 权重矩阵的约束函数。默认值：None。
recurrent_constraint 应用于recurrent_kernel 权重矩阵的约束函数。默认值：None。
bias_constraint 应用于偏置向量的约束函数。默认值：None。
dropout 在 0 和 1 之间浮点数。为输入的线性变换而下降的单位分数。默认值：0。
recurrent_dropout 在 0 和 1 之间浮点数。用于循环状态的线性变换的单位的分数。默认值：0。
return_sequences 布尔值。是返回输出序列中的最后一个输出，还是返回完整序列。默认值：False。
return_state 布尔值。是否返回除了输出之外的最后一个状态。默认值：False。
go_backwards 布尔值(默认 False )。如果为 True，则反向处理输入序列并返回反向序列。
stateful 布尔值(默认为 False)。如果为 True，则批次中索引 i 处每个样本的最后状态将用作下一批中索引 i 的样本的初始状态。
unroll 布尔值(默认为 False)。如果为 True，则网络将展开，否则将使用符号循环。展开可以speed-up一个RNN，虽然它往往更多memory-intensive。展开仅适用于短序列。
time_major inputs 和 outputs 张量的形状格式。如果为 True，输入和输出的形状将是 [timesteps, batch, feature] ，而在 False 情况下，它将是 [batch, timesteps, feature] 。使用time_major = True 效率更高一些，因为它避免了 RNN 计算开始和结束时的转置。但是，大多数 TensorFlow 数据是 batch-major，因此默认情况下，此函数接受输入并以 batch-major 形式发出输出。
reset_after GRU 约定(是否在矩阵乘法之后或之前应用重置门)。 False = "before"，True = "after"(默认和 cuDNN 兼容)。
```

- 属性

```
activation
bias_constraint
bias_initializer
bias_regularizer
dropout
implementation
kernel_constraint
kernel_initializer
kernel_regularizer
recurrent_activation
recurrent_constraint
recurrent_dropout
recurrent_initializer
recurrent_regularizer
reset_after
states
units
use_bias
```

有关 RNN API 使用的详细信息，请参阅 Keras RNN API 指南。

根据可用的运行时硬件和约束，该层将选择不同的实现(基于 cuDNN 或 pure-TensorFlow)以最大化性能。如果 GPU 可用并且该层的所有参数都满足 cuDNN 内核的要求(详见下文)，则该层将使用快速 cuDNN 实现。

使用 cuDNN 实现的要求是：
```
activation == tanh
recurrent_activation == sigmoid
recurrent_dropout == 0
unroll 是 False
use_bias 是 True
reset_after 是 True
```
输入，如果使用掩码，严格来说是right-padded。
在最外层的上下文中启用了即刻执行。
GRU 实现有两种变体。默认的基于 v3，并在矩阵乘法之前将重置门应用于隐藏状态。另一种是根据原件，顺序颠倒。

第二个变体与 CuDNNGRU (GPU-only) 兼容，并允许在 CPU 上进行推理。因此，它对 kernel 和 recurrent_kernel 有不同的偏见。要使用此变体，请设置 reset_after=True 和 recurrent_activation='sigmoid' 。

例如：
```
inputs = tf.random.normal([32, 10, 8])
gru = tf.keras.layers.GRU(4)
output = gru(inputs)
print(output.shape)
(32, 4)
gru = tf.keras.layers.GRU(4, return_sequences=True, return_state=True)
whole_sequence_output, final_state = gru(inputs)
print(whole_sequence_output.shape)
(32, 10, 4)
print(final_state.shape)
(32, 4)
```

调用参数：
inputs:一个 3D 张量，有形状[batch, timesteps, feature].
mask: 形状的二进制张量[samples, timesteps]指示是否应屏蔽给定时间步(可选，默认为None)。个人True条目指示应使用相应的时间步长，而Falseentry 表示应该忽略相应的时间步长。
training:Python 布尔值，指示层应该在训练模式还是推理模式下运行。此参数在调用时传递给单元格。这仅在以下情况下才相关dropout或者recurrent_dropout使用(可选，默认为None)。
initial_state：要传递给单元格第一次调用的初始状态张量列表(可选，默认为None这会导致创建zero-filled 初始状态张量)。

In [11]:
gru = keras.layers.GRU(units, return_sequences=True, return_state=True,
                                       recurrent_initializer="glorot_uniform")

In [12]:
help(gru)

Help on GRU in module keras.layers.recurrent_v2 object:

class GRU(keras.layers.recurrent.DropoutRNNCellMixin, keras.layers.recurrent.GRU)
 |  Gated Recurrent Unit - Cho et al. 2014.
 |  
 |  See [the Keras RNN API guide](https://www.tensorflow.org/guide/keras/rnn)
 |  for details about the usage of RNN API.
 |  
 |  Based on available runtime hardware and constraints, this layer
 |  will choose different implementations (cuDNN-based or pure-TensorFlow)
 |  to maximize the performance. If a GPU is available and all
 |  the arguments to the layer meet the requirement of the CuDNN kernel
 |  (see below for details), the layer will use a fast cuDNN implementation.
 |  
 |  The requirements to use the cuDNN implementation are:
 |  
 |  1. `activation` == `tanh`
 |  2. `recurrent_activation` == `sigmoid`
 |  3. `recurrent_dropout` == 0
 |  4. `unroll` is `False`
 |  5. `use_bias` is `True`
 |  6. `reset_after` is `True`
 |  7. Inputs, if use masking, are strictly right-padded.
 |  8. Eager 

In [13]:
embed_x =embed(test_x)
embed_x

<tf.Tensor: shape=(32, 2, 10), dtype=float32, numpy=
array([[[-0.04455454,  0.04463908,  0.04506776,  0.02344776,
         -0.04919156, -0.04341774, -0.0441567 ,  0.01678076,
         -0.01249163,  0.0438653 ],
        [-0.0176981 , -0.02319922,  0.01458457, -0.02064159,
          0.01132836,  0.00938264, -0.04608802, -0.01562606,
          0.04889529, -0.02774007]],

       [[-0.04455454,  0.04463908,  0.04506776,  0.02344776,
         -0.04919156, -0.04341774, -0.0441567 ,  0.01678076,
         -0.01249163,  0.0438653 ],
        [ 0.01003499,  0.0396397 , -0.02368988, -0.0179203 ,
         -0.02464662,  0.04157648,  0.00130557,  0.04739784,
         -0.01525488, -0.04575637]],

       [[-0.02027046,  0.04145514,  0.00930665,  0.03462258,
          0.03842961,  0.00826417, -0.04229715, -0.02322576,
          0.01806841,  0.03489599],
        [-0.02027046,  0.04145514,  0.00930665,  0.03462258,
          0.03842961,  0.00826417, -0.04229715, -0.02322576,
          0.01806841,  0.034895

In [14]:
init_hidden = tf.zeros((batch_size, units))
init_hidden

<tf.Tensor: shape=(32, 32), dtype=float32, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>

In [15]:
output_x, state_x=gru(embed_x,init_hidden)

In [16]:
output_x

<tf.Tensor: shape=(32, 2, 32), dtype=float32, numpy=
array([[[-8.78948532e-03,  1.13781048e-02,  7.73639930e-03, ...,
         -2.38645985e-03,  3.35185975e-03, -8.87926482e-03],
        [-8.53142608e-03, -2.90199416e-03,  6.60363911e-03, ...,
         -5.99072827e-03,  6.21979198e-05, -1.53577607e-02]],

       [[-8.78948532e-03,  1.13781048e-02,  7.73639930e-03, ...,
         -2.38645985e-03,  3.35185975e-03, -8.87926482e-03],
        [-4.27575875e-03,  1.69663895e-02,  3.32427351e-03, ...,
         -5.13378670e-03,  5.40198432e-03,  3.86977615e-03]],

       [[-1.13754757e-02, -7.46724149e-03, -4.30806016e-04, ...,
         -2.78959423e-03,  4.35484726e-05, -7.74714025e-03],
        [-1.71657223e-02, -1.16010411e-02, -7.78712129e-05, ...,
         -3.85822030e-03, -1.23892841e-03, -1.20907454e-02]],

       ...,

       [[-8.78948532e-03,  1.13781048e-02,  7.73639930e-03, ...,
         -2.38645985e-03,  3.35185975e-03, -8.87926482e-03],
        [-4.98111267e-03,  9.80127021e-04,  7.

In [17]:
state_x

<tf.Tensor: shape=(32, 32), dtype=float32, numpy=
array([[-8.53142608e-03, -2.90199416e-03,  6.60363911e-03, ...,
        -5.99072827e-03,  6.21979198e-05, -1.53577607e-02],
       [-4.27575875e-03,  1.69663895e-02,  3.32427351e-03, ...,
        -5.13378670e-03,  5.40198432e-03,  3.86977615e-03],
       [-1.71657223e-02, -1.16010411e-02, -7.78712129e-05, ...,
        -3.85822030e-03, -1.23892841e-03, -1.20907454e-02],
       ...,
       [-4.98111267e-03,  9.80127021e-04,  7.48883816e-04, ...,
         1.01228440e-02,  4.80283331e-03, -4.67822142e-03],
       [ 3.57209658e-03,  7.32741039e-03, -3.10522295e-03, ...,
        -7.78462272e-03, -2.90061347e-03,  7.98213482e-03],
       [ 1.01556834e-04,  8.98117479e-03, -2.51522078e-03, ...,
         1.32623105e-03, -2.10925913e-03,  9.06594470e-03]], dtype=float32)>

### tf.expand_dims()函数用于给函数增加维度。

```
tf.expand_dims()函数用于给函数增加维度。
tf.expand_dims(
    input,
    axis=None,
    name=None,
    dim=None
)
```
参数：
```
input是输入张量。
axis是指定扩大输入张量形状的维度索引值。
dim等同于轴，一般不推荐使用。
```
函数的功能是在给定一个input时，在axis轴处给input增加一个维度。

- axis：

给定张量输入input，此操作为选择维度索引值，在输入形状的维度索引值的轴处插入1的维度。 维度索引值的轴从零开始; 如果您指定轴是负数，则从最后向后进行计数，也就是倒数。

In [54]:
test_y=tf.expand_dims([0]*batch_size,1)
test_y

<tf.Tensor: shape=(32, 1), dtype=int32, numpy=
array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])>

In [19]:
tf.expand_dims(0, 0)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([0])>

In [20]:
fc = keras.layers.Dense(vocab_size)

In [21]:
fc

In [22]:
hidden_y = [tf.zeros((1, units))]

In [23]:
hidden_y

[<tf.Tensor: shape=(1, 32), dtype=float32, numpy=
 array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
       dtype=float32)>]

In [24]:
tf.expand_dims(state_x, 1)

<tf.Tensor: shape=(32, 1, 32), dtype=float32, numpy=
array([[[-8.53142608e-03, -2.90199416e-03,  6.60363911e-03, ...,
         -5.99072827e-03,  6.21979198e-05, -1.53577607e-02]],

       [[-4.27575875e-03,  1.69663895e-02,  3.32427351e-03, ...,
         -5.13378670e-03,  5.40198432e-03,  3.86977615e-03]],

       [[-1.71657223e-02, -1.16010411e-02, -7.78712129e-05, ...,
         -3.85822030e-03, -1.23892841e-03, -1.20907454e-02]],

       ...,

       [[-4.98111267e-03,  9.80127021e-04,  7.48883816e-04, ...,
          1.01228440e-02,  4.80283331e-03, -4.67822142e-03]],

       [[ 3.57209658e-03,  7.32741039e-03, -3.10522295e-03, ...,
         -7.78462272e-03, -2.90061347e-03,  7.98213482e-03]],

       [[ 1.01556834e-04,  8.98117479e-03, -2.51522078e-03, ...,
          1.32623105e-03, -2.10925913e-03,  9.06594470e-03]]],
      dtype=float32)>

In [25]:
W1 = keras.layers.Dense(units)
W2 = keras.layers.Dense(units)
V = keras.layers.Dense(1)

In [53]:
embed(test_y)

<tf.Tensor: shape=(32, 1, 2, 10), dtype=float32, numpy=
array([[[[-0.00582673,  0.01700796, -0.0066212 , -0.03161768,
          -0.01707266,  0.03116467,  0.01597368, -0.01423205,
          -0.01439886, -0.01674361],
         [-0.00582673,  0.01700796, -0.0066212 , -0.03161768,
          -0.01707266,  0.03116467,  0.01597368, -0.01423205,
          -0.01439886, -0.01674361]]],


       [[[-0.00401158,  0.02691047, -0.04453013, -0.03804395,
          -0.04162438, -0.01433868, -0.04531867,  0.02753348,
           0.01271724, -0.02674476],
         [-0.02563901, -0.01560853,  0.012044  ,  0.01931993,
          -0.03744175,  0.03179225, -0.04118588, -0.01800214,
           0.01870343,  0.01538343]]],


       [[[-0.04455454,  0.04463908,  0.04506776,  0.02344776,
          -0.04919156, -0.04341774, -0.0441567 ,  0.01678076,
          -0.01249163,  0.0438653 ],
         [ 0.00118176, -0.00458641, -0.00565982, -0.04272276,
           0.03841951, -0.04602567, -0.00741174, -0.01831134,
       

In [27]:
W1(output_x)

<tf.Tensor: shape=(32, 2, 32), dtype=float32, numpy=
array([[[ 0.01029635,  0.00148423,  0.00549972, ...,  0.00598448,
         -0.01493043,  0.00105774],
        [ 0.00468471,  0.00159314, -0.00014553, ...,  0.00482081,
         -0.01243681, -0.00836829]],

       [[ 0.01029635,  0.00148423,  0.00549972, ...,  0.00598448,
         -0.01493043,  0.00105774],
        [ 0.01216146, -0.00312846,  0.01049282, ...,  0.00014848,
         -0.00028515, -0.00459104]],

       [[ 0.00205284,  0.00271043, -0.0028394 , ...,  0.00756163,
         -0.00707033, -0.00189234],
        [ 0.00357856,  0.00420283, -0.00433349, ...,  0.01169347,
         -0.01025148, -0.00278315]],

       ...,

       [[ 0.01029635,  0.00148423,  0.00549972, ...,  0.00598448,
         -0.01493043,  0.00105774],
        [-0.00487379, -0.00513739,  0.0009195 , ...,  0.00571866,
         -0.0025768 , -0.00019166]],

       [[ 0.00080834,  0.00201335,  0.00551351, ..., -0.01267827,
          0.00227052,  0.00325649],
        

In [28]:
W2(tf.expand_dims(state_x, 1))

<tf.Tensor: shape=(32, 1, 32), dtype=float32, numpy=
array([[[-0.00513653, -0.01047728, -0.00045647, ..., -0.00154757,
         -0.00178081,  0.01662941]],

       [[ 0.0046214 ,  0.00318803,  0.00460281, ..., -0.0096824 ,
         -0.00314243, -0.01308868]],

       [[-0.00207403, -0.01013148,  0.00273078, ...,  0.00146232,
         -0.00381819,  0.00718357]],

       ...,

       [[-0.01347445, -0.00428144,  0.00013697, ..., -0.00117883,
         -0.00402178,  0.01163399]],

       [[ 0.00279944,  0.00287612, -0.00194468, ..., -0.00280624,
          0.00435776, -0.00834067]],

       [[-0.00133585,  0.00107002, -0.00105409, ..., -0.00324946,
          0.00073775, -0.00378133]]], dtype=float32)>

In [32]:
W1(output_x)+W2(tf.expand_dims(state_x, 1))[0]

<tf.Tensor: shape=(32, 2, 32), dtype=float32, numpy=
array([[[ 5.1598260e-03, -8.9930501e-03,  5.0432440e-03, ...,
          4.4369092e-03, -1.6711244e-02,  1.7687155e-02],
        [-4.5181904e-04, -8.8841394e-03, -6.0200389e-04, ...,
          3.2732380e-03, -1.4217618e-02,  8.2611218e-03]],

       [[ 5.1598260e-03, -8.9930501e-03,  5.0432440e-03, ...,
          4.4369092e-03, -1.6711244e-02,  1.7687155e-02],
        [ 7.0249299e-03, -1.3605742e-02,  1.0036348e-02, ...,
         -1.3990933e-03, -2.0659592e-03,  1.2038375e-02]],

       [[-3.0836826e-03, -7.7668540e-03, -3.2958761e-03, ...,
          6.0140593e-03, -8.8511426e-03,  1.4737076e-02],
        [-1.5579653e-03, -6.2744492e-03, -4.7899582e-03, ...,
          1.0145903e-02, -1.2032293e-02,  1.3846265e-02]],

       ...,

       [[ 5.1598260e-03, -8.9930501e-03,  5.0432440e-03, ...,
          4.4369092e-03, -1.6711244e-02,  1.7687155e-02],
        [-1.0010317e-02, -1.5614673e-02,  4.6302844e-04, ...,
          4.1710925e-03, -

In [30]:
W1(output_x)[0]

<tf.Tensor: shape=(2, 32), dtype=float32, numpy=
array([[ 0.01029635,  0.00148423,  0.00549972,  0.00289583, -0.01529934,
        -0.00110411,  0.00214484, -0.0037445 , -0.01671661, -0.00739318,
         0.00232342,  0.01436429,  0.00534583,  0.00994391,  0.01382414,
         0.01220044,  0.00159514, -0.00685544,  0.00646889,  0.00529287,
         0.01438059,  0.00312169, -0.00390364,  0.00990993,  0.01294299,
        -0.01431926, -0.0056556 ,  0.00897159,  0.00214641,  0.00598448,
        -0.01493043,  0.00105774],
       [ 0.00468471,  0.00159314, -0.00014553,  0.01112385, -0.01260095,
        -0.00549098,  0.00533292, -0.00307141,  0.00259329, -0.00415351,
        -0.00647227,  0.00984916,  0.00214036,  0.00155237,  0.01105889,
        -0.0082521 ,  0.00606149, -0.00575504, -0.00234239,  0.00660378,
         0.00276902,  0.00408481,  0.00526104,  0.00867581,  0.02541972,
        -0.00263549, -0.01172028,  0.01250698,  0.00290068,  0.00482081,
        -0.01243681, -0.00836829]], dtyp

In [31]:
W2(tf.expand_dims(state_x, 1))[0]

<tf.Tensor: shape=(1, 32), dtype=float32, numpy=
array([[-0.00513653, -0.01047728, -0.00045647,  0.00573935, -0.00897936,
        -0.0152008 , -0.00637342,  0.00083789,  0.01351233,  0.0084723 ,
         0.00138286,  0.0017098 , -0.00738968, -0.01253817,  0.00373444,
        -0.00298303, -0.00039392, -0.01606884,  0.0044345 , -0.00147224,
         0.002454  ,  0.00040417,  0.00048474,  0.01082856,  0.01240887,
         0.00326927,  0.00602526,  0.0012772 , -0.00555167, -0.00154757,
        -0.00178081,  0.01662941]], dtype=float32)>

In [33]:
W1(output_x)+W2(tf.expand_dims(state_x, 1))

<tf.Tensor: shape=(32, 2, 32), dtype=float32, numpy=
array([[[ 5.15982602e-03, -8.99305008e-03,  5.04324399e-03, ...,
          4.43690922e-03, -1.67112444e-02,  1.76871549e-02],
        [-4.51819040e-04, -8.88413936e-03, -6.02003885e-04, ...,
          3.27323796e-03, -1.42176179e-02,  8.26112181e-03]],

       [[ 1.49177574e-02,  4.67226002e-03,  1.01025235e-02, ...,
         -3.69791454e-03, -1.80728585e-02, -1.20309349e-02],
        [ 1.67828612e-02,  5.95687889e-05,  1.50956279e-02, ...,
         -9.53391753e-03, -3.42757348e-03, -1.76797137e-02]],

       [[-2.11829320e-05, -7.42104929e-03, -1.08622946e-04, ...,
          9.02394671e-03, -1.08885225e-02,  5.29123470e-03],
        [ 1.50453439e-03, -5.92864444e-03, -1.60270510e-03, ...,
          1.31557891e-02, -1.40696727e-02,  4.40042419e-03]],

       ...,

       [[-3.17809545e-03, -2.79720570e-03,  5.63668367e-03, ...,
          4.80564870e-03, -1.89522132e-02,  1.26917288e-02],
        [-1.83482394e-02, -9.41882841e-03,  1.

In [34]:
tf.nn.tanh(W1(output_x)+W2(tf.expand_dims(state_x, 1)))

<tf.Tensor: shape=(32, 2, 32), dtype=float32, numpy=
array([[[ 5.15977945e-03, -8.99280701e-03,  5.04320068e-03, ...,
          4.43687942e-03, -1.67096872e-02,  1.76853091e-02],
        [-4.51818953e-04, -8.88390467e-03, -6.02003711e-04, ...,
          3.27322609e-03, -1.42166587e-02,  8.26093275e-03]],

       [[ 1.49166491e-02,  4.67222556e-03,  1.01021798e-02, ...,
         -3.69789731e-03, -1.80708896e-02, -1.20303538e-02],
        [ 1.67812835e-02,  5.95687889e-05,  1.50944795e-02, ...,
         -9.53362789e-03, -3.42755998e-03, -1.76778696e-02]],

       [[-2.11829320e-05, -7.42091192e-03, -1.08622946e-04, ...,
          9.02370084e-03, -1.08880904e-02,  5.29118488e-03],
        [ 1.50453311e-03, -5.92857460e-03, -1.60270371e-03, ...,
          1.31550292e-02, -1.40687441e-02,  4.40039532e-03]],

       ...,

       [[-3.17808450e-03, -2.79719825e-03,  5.63662313e-03, ...,
          4.80561145e-03, -1.89499427e-02,  1.26910452e-02],
        [-1.83461793e-02, -9.41854902e-03,  1.

In [36]:
V(tf.nn.tanh(W1(output_x)+W2(tf.expand_dims(state_x, 1))))

<tf.Tensor: shape=(32, 2, 1), dtype=float32, numpy=
array([[[ 7.79337436e-03],
        [-1.72917242e-03]],

       [[-7.97312893e-03],
        [-2.02629548e-02]],

       [[-8.66569113e-04],
        [ 2.18018447e-03]],

       [[ 1.05049449e-03],
        [-1.20109087e-03]],

       [[ 1.00703212e-02],
        [ 1.19689591e-02]],

       [[ 1.20761711e-02],
        [ 8.32181331e-03]],

       [[-1.47455223e-02],
        [-1.97050255e-02]],

       [[ 6.47079805e-03],
        [ 8.35466012e-03]],

       [[-7.58036331e-04],
        [ 4.37178998e-04]],

       [[ 9.06376867e-04],
        [ 5.69616072e-03]],

       [[ 6.05362281e-03],
        [-2.64034607e-05]],

       [[-1.53386500e-03],
        [-3.36065050e-03]],

       [[ 5.44138858e-03],
        [ 1.10795945e-02]],

       [[ 1.01707028e-02],
        [ 4.98454971e-03]],

       [[-1.27204508e-03],
        [-3.09423730e-03]],

       [[ 2.74671428e-03],
        [ 6.02369988e-03]],

       [[-9.19098500e-03],
        [-6.95762690e-04]

In [37]:
tf.nn.softmax(V(tf.nn.tanh(W1(output_x)+W2(tf.expand_dims(state_x, 1)))))

<tf.Tensor: shape=(32, 2, 1), dtype=float32, numpy=
array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
    

In [38]:
tf.nn.softmax(V(tf.nn.tanh(W1(output_x)+W2(tf.expand_dims(state_x, 1)))),axis=1)

<tf.Tensor: shape=(32, 2, 1), dtype=float32, numpy=
array([[[0.5023806 ],
        [0.49761936]],

       [[0.50307244],
        [0.4969276 ]],

       [[0.4992383 ],
        [0.5007617 ]],

       [[0.5005629 ],
        [0.49943712]],

       [[0.49952537],
        [0.5004747 ]],

       [[0.5009386 ],
        [0.4990614 ]],

       [[0.50123984],
        [0.49876013]],

       [[0.49952903],
        [0.50047094]],

       [[0.4997012 ],
        [0.5002988 ]],

       [[0.49880257],
        [0.50119746]],

       [[0.50152   ],
        [0.49847996]],

       [[0.5004567 ],
        [0.4995433 ]],

       [[0.49859047],
        [0.50140953]],

       [[0.5012965 ],
        [0.49870345]],

       [[0.50045556],
        [0.49954444]],

       [[0.49918073],
        [0.5008192 ]],

       [[0.49787623],
        [0.5021238 ]],

       [[0.50244886],
        [0.49755117]],

       [[0.50128484],
        [0.4987152 ]],

       [[0.49795446],
        [0.5020455 ]],

       [[0.49784675],
      

In [42]:
tf.nn.softmax(V(tf.nn.tanh(W1(output_x)+W2(tf.expand_dims(state_x, 1)))),axis=1) * output_x

<tf.Tensor: shape=(32, 2, 32), dtype=float32, numpy=
array([[[-4.4156672e-03,  5.7161395e-03,  3.8866170e-03, ...,
         -1.1989111e-03,  1.6839093e-03, -4.4607706e-03],
        [-4.2454028e-03, -1.4440885e-03,  3.2860986e-03, ...,
         -2.9811023e-03,  3.0950891e-05, -7.6423190e-03]],

       [[-4.4217478e-03,  5.7240110e-03,  3.8919693e-03, ...,
         -1.2005622e-03,  1.6862282e-03, -4.4669136e-03],
        [-2.1247424e-03,  8.4310668e-03,  1.6519232e-03, ...,
         -2.5511202e-03,  2.6843951e-03,  1.9229986e-03]],

       [[-5.6790733e-03, -3.7279329e-03, -2.1507486e-04, ...,
         -1.3926723e-03,  2.1741065e-05, -3.8676693e-03],
        [-8.5959360e-03, -5.8093569e-03, -3.8994920e-05, ...,
         -1.9320489e-03, -6.2040787e-04, -6.0545821e-03]],

       ...,

       [[-4.4001467e-03,  5.6960480e-03,  3.8729561e-03, ...,
         -1.1946972e-03,  1.6779907e-03, -4.4450914e-03],
        [-2.4874939e-03,  4.8946089e-04,  3.7398149e-04, ...,
          5.0551984e-03,  

In [44]:
tf.reduce_sum(tf.nn.softmax(V(tf.nn.tanh(W1(output_x)+W2(tf.expand_dims(state_x, 1)))),axis=1) * output_x, axis=1)

<tf.Tensor: shape=(32, 32), dtype=float32, numpy=
array([[-0.00866107,  0.00427205,  0.00717272, ..., -0.00418001,
         0.00171486, -0.01210309],
       [-0.00654649,  0.01415508,  0.00554389, ..., -0.00375168,
         0.00437062, -0.00254392],
       [-0.01427501, -0.00953729, -0.00025407, ..., -0.00332472,
        -0.00059867, -0.00992225],
       ...,
       [-0.00688764,  0.00618551,  0.00424694, ...,  0.0038605 ,
         0.00407645, -0.00678133],
       [ 0.00220317,  0.00525951, -0.00274464, ..., -0.00316809,
        -0.00324817,  0.00704863],
       [-0.00051767,  0.00951949, -0.00109376, ...,  0.00017664,
         0.00023785,  0.00677408]], dtype=float32)>

In [45]:
tf.expand_dims(tf.reduce_sum(tf.nn.softmax(V(tf.nn.tanh(W1(output_x)+W2(tf.expand_dims(state_x, 1)))),axis=1) * output_x, axis=1) , 1)

<tf.Tensor: shape=(32, 1, 32), dtype=float32, numpy=
array([[[-0.00866107,  0.00427205,  0.00717272, ..., -0.00418001,
          0.00171486, -0.01210309]],

       [[-0.00654649,  0.01415508,  0.00554389, ..., -0.00375168,
          0.00437062, -0.00254392]],

       [[-0.01427501, -0.00953729, -0.00025407, ..., -0.00332472,
         -0.00059867, -0.00992225]],

       ...,

       [[-0.00688764,  0.00618551,  0.00424694, ...,  0.0038605 ,
          0.00407645, -0.00678133]],

       [[ 0.00220317,  0.00525951, -0.00274464, ..., -0.00316809,
         -0.00324817,  0.00704863]],

       [[-0.00051767,  0.00951949, -0.00109376, ...,  0.00017664,
          0.00023785,  0.00677408]]], dtype=float32)>

In [57]:
tf.concat([tf.expand_dims(tf.reduce_sum(tf.nn.softmax(V(tf.nn.tanh(W1(output_x)+W2(tf.expand_dims(state_x, 1)))),axis=1) * output_x, axis=1) , 1), embed(test_y)],axis=-1)

<tf.Tensor: shape=(32, 1, 42), dtype=float32, numpy=
array([[[-0.00866107,  0.00427205,  0.00717272, ..., -0.02322576,
          0.01806841,  0.03489599]],

       [[-0.00654649,  0.01415508,  0.00554389, ..., -0.02322576,
          0.01806841,  0.03489599]],

       [[-0.01427501, -0.00953729, -0.00025407, ..., -0.02322576,
          0.01806841,  0.03489599]],

       ...,

       [[-0.00688764,  0.00618551,  0.00424694, ..., -0.02322576,
          0.01806841,  0.03489599]],

       [[ 0.00220317,  0.00525951, -0.00274464, ..., -0.02322576,
          0.01806841,  0.03489599]],

       [[-0.00051767,  0.00951949, -0.00109376, ..., -0.02322576,
          0.01806841,  0.03489599]]], dtype=float32)>

In [59]:
gru1 = keras.layers.GRU(units, return_sequences=True, return_state=True,
                                       recurrent_initializer="glorot_uniform")

In [60]:
gru1(tf.concat([tf.expand_dims(tf.reduce_sum(tf.nn.softmax(V(tf.nn.tanh(W1(output_x)+W2(tf.expand_dims(state_x, 1)))),axis=1) * output_x, axis=1) , 1), embed(test_y)],axis=-1))

[<tf.Tensor: shape=(32, 1, 32), dtype=float32, numpy=
 array([[[ 0.00036771,  0.00946481,  0.00336648, ..., -0.00062484,
          -0.00501798, -0.00876475]],
 
        [[ 0.00011893,  0.00942861,  0.00669399, ..., -0.00020584,
          -0.00579007, -0.00790557]],
 
        [[-0.00124503,  0.00480166,  0.00167328, ..., -0.00205437,
          -0.0050885 , -0.00797837]],
 
        ...,
 
        [[-0.00190381,  0.00823201,  0.00451687, ..., -0.00213723,
          -0.00405872, -0.00935513]],
 
        [[-0.00132481,  0.0058695 ,  0.0035357 , ...,  0.00239262,
          -0.00535032, -0.00917497]],
 
        [[-0.00097965,  0.00704645,  0.00501177, ...,  0.00049192,
          -0.00489612, -0.0074265 ]]], dtype=float32)>,
 <tf.Tensor: shape=(32, 32), dtype=float32, numpy=
 array([[ 0.00036771,  0.00946481,  0.00336648, ..., -0.00062484,
         -0.00501798, -0.00876475],
        [ 0.00011893,  0.00942861,  0.00669399, ..., -0.00020584,
         -0.00579007, -0.00790557],
        [-0.001245

In [61]:
output_y, state_y = gru1(tf.concat([tf.expand_dims(tf.reduce_sum(tf.nn.softmax(V(tf.nn.tanh(W1(output_x)+W2(tf.expand_dims(state_x, 1)))),axis=1) * output_x, axis=1) , 1), embed(test_y)],axis=-1))

In [62]:
output_y

<tf.Tensor: shape=(32, 1, 32), dtype=float32, numpy=
array([[[ 0.00036771,  0.00946481,  0.00336648, ..., -0.00062484,
         -0.00501798, -0.00876475]],

       [[ 0.00011893,  0.00942861,  0.00669399, ..., -0.00020584,
         -0.00579007, -0.00790557]],

       [[-0.00124503,  0.00480166,  0.00167328, ..., -0.00205437,
         -0.0050885 , -0.00797837]],

       ...,

       [[-0.00190381,  0.00823201,  0.00451687, ..., -0.00213723,
         -0.00405872, -0.00935513]],

       [[-0.00132481,  0.0058695 ,  0.0035357 , ...,  0.00239262,
         -0.00535032, -0.00917497]],

       [[-0.00097965,  0.00704645,  0.00501177, ...,  0.00049192,
         -0.00489612, -0.0074265 ]]], dtype=float32)>

In [63]:
state_y

<tf.Tensor: shape=(32, 32), dtype=float32, numpy=
array([[ 0.00036771,  0.00946481,  0.00336648, ..., -0.00062484,
        -0.00501798, -0.00876475],
       [ 0.00011893,  0.00942861,  0.00669399, ..., -0.00020584,
        -0.00579007, -0.00790557],
       [-0.00124503,  0.00480166,  0.00167328, ..., -0.00205437,
        -0.0050885 , -0.00797837],
       ...,
       [-0.00190381,  0.00823201,  0.00451687, ..., -0.00213723,
        -0.00405872, -0.00935513],
       [-0.00132481,  0.0058695 ,  0.0035357 , ...,  0.00239262,
        -0.00535032, -0.00917497],
       [-0.00097965,  0.00704645,  0.00501177, ...,  0.00049192,
        -0.00489612, -0.0074265 ]], dtype=float32)>

In [66]:
(-1,output_y.shape[2])

(-1, 32)

In [67]:
tf.reshape(output_y, (-1,output_y.shape[2]))

<tf.Tensor: shape=(32, 32), dtype=float32, numpy=
array([[ 0.00036771,  0.00946481,  0.00336648, ..., -0.00062484,
        -0.00501798, -0.00876475],
       [ 0.00011893,  0.00942861,  0.00669399, ..., -0.00020584,
        -0.00579007, -0.00790557],
       [-0.00124503,  0.00480166,  0.00167328, ..., -0.00205437,
        -0.0050885 , -0.00797837],
       ...,
       [-0.00190381,  0.00823201,  0.00451687, ..., -0.00213723,
        -0.00405872, -0.00935513],
       [-0.00132481,  0.0058695 ,  0.0035357 , ...,  0.00239262,
        -0.00535032, -0.00917497],
       [-0.00097965,  0.00704645,  0.00501177, ...,  0.00049192,
        -0.00489612, -0.0074265 ]], dtype=float32)>

In [68]:
fc1 = keras.layers.Dense(vocab_size)

In [69]:
fc1(tf.reshape(output_y, (-1,output_y.shape[2])))

<tf.Tensor: shape=(32, 10), dtype=float32, numpy=
array([[-5.95972361e-03,  2.77436059e-03, -2.20011547e-03,
         7.65925134e-03, -1.45629831e-02,  2.78214971e-03,
         2.06288183e-03,  1.90507702e-03,  6.89866347e-03,
         6.51487662e-03],
       [-1.00120995e-02,  1.84332626e-03, -5.50950971e-03,
         7.76329171e-03, -1.39553417e-02,  2.70068343e-03,
         6.03591278e-03, -5.99945080e-04,  9.27803107e-03,
         4.61826753e-03],
       [-6.15117420e-03,  3.11450218e-03,  1.76435639e-03,
         8.00396502e-03, -1.19071109e-02,  4.74305637e-03,
        -3.70908342e-03,  4.13117814e-04,  6.21915981e-03,
         8.54632352e-03],
       [-1.33094226e-03,  3.41514708e-03,  7.63795245e-03,
         4.21474548e-03, -1.23214470e-02,  3.29726026e-03,
        -6.63302280e-03,  4.98001929e-03,  3.07544251e-03,
         6.20615017e-03],
       [-8.92779045e-03, -1.04309223e-03,  3.75626446e-03,
         1.02804909e-02, -1.26910694e-02,  5.61295403e-03,
        -6.35087490e